# Generated by Django 4.0.2 on 2022-03-06 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'banner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, null=True)),
                ('types', models.CharField(blank=True, max_length=255, null=True)),
                ('desc_snippet', models.TextField(blank=True, null=True)),
                ('recent_reviews', models.TextField(blank=True, null=True)),
                ('all_reviews', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=255, null=True)),
                ('developer', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
                ('popular_tags', models.TextField(blank=True, null=True)),
                ('game_details', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('achievements', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('game_description', models.TextField(blank=True, null=True)),
                ('mature_content', models.TextField(blank=True, null=True)),
                ('minimum_requirements', models.TextField(blank=True, null=True)),
                ('recommended_requirements', models.TextField(blank=True, null=True)),
                ('original_price', models.CharField(blank=True, max_length=255, null=True)),
                ('discount_price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'game_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recommend1',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('game1', models.CharField(max_length=255)),
                ('game2', models.CharField(max_length=255)),
                ('game3', models.CharField(max_length=255)),
                ('game4', models.CharField(max_length=255)),
                ('game5', models.CharField(max_length=255)),
                ('game6', models.CharField(max_length=255)),
                ('game7', models.CharField(max_length=255)),
                ('game8', models.CharField(max_length=255)),
                ('game9', models.CharField(max_length=255)),
                ('game10', models.CharField(max_length=255)),
                ('game11', models.CharField(max_length=255)),
                ('game12', models.CharField(max_length=255)),
                ('game13', models.CharField(max_length=255)),
                ('game14', models.CharField(max_length=255)),
                ('game15', models.CharField(max_length=255)),
                ('game16', models.CharField(max_length=255)),
                ('game17', models.CharField(max_length=255)),
                ('game18', models.CharField(max_length=255)),
                ('game19', models.CharField(max_length=255)),
                ('game20', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'recommend1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recommend2',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('game1', models.CharField(max_length=255)),
                ('game2', models.CharField(max_length=255)),
                ('game3', models.CharField(max_length=255)),
                ('game4', models.CharField(max_length=255)),
                ('game5', models.CharField(max_length=255)),
                ('game6', models.CharField(max_length=255)),
                ('game7', models.CharField(max_length=255)),
                ('game8', models.CharField(max_length=255)),
                ('game9', models.CharField(max_length=255)),
                ('game10', models.CharField(max_length=255)),
                ('game11', models.CharField(max_length=255)),
                ('game12', models.CharField(max_length=255)),
                ('game13', models.CharField(max_length=255)),
                ('game14', models.CharField(max_length=255)),
                ('game15', models.CharField(max_length=255)),
                ('game16', models.CharField(max_length=255)),
                ('game17', models.CharField(max_length=255)),
                ('game18', models.CharField(max_length=255)),
                ('game19', models.CharField(max_length=255)),
                ('game20', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'recommend2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('game_name', models.CharField(max_length=255)),
                ('hours', models.FloatField()),
                ('purchase', models.IntegerField()),
                ('play', models.IntegerField()),
            ],
            options={
                'db_table': 'repository',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('qq', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player',
                'managed': True,
            },
        ),
    ]
