# Generated by Django 4.0.2 on 2022-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('img_url', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rank',
                'managed': True,
            },
        ),
    ]
