# Generated by Django 4.0.2 on 2022-03-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerank',
            name='discount_pct',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamerank',
            name='discount_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gamerank',
            name='publish_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
