# Generated by Django 4.0.2 on 2022-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_gamerank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerank',
            name='rank_type',
            field=models.CharField(default='hot', max_length=255),
        ),
    ]
